apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend-service
spec:
  selector:
    app: task-manager-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
