apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: task-manager-config
    behavior: merge
    literals:
      - NODE_ENV=staging
