apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- replica-patch.yaml
- resources-patch.yaml

configMapGenerator:
- behavior: merge
  literals:
  - NODE_ENV=production
  name: task-manager-config

images:
- name: task-manager-backend
- name: task-manager-frontend
