apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - resources-patch.yaml

configMapGenerator:
  - name: task-manager-config
    behavior: merge
    literals:
      - NODE_ENV=production

images:
  - name: task-manager-frontend
    newName: your-registry/task-manager-frontend
    newTag: latest
  - name: task-manager-backend
    newName: your-registry/task-manager-backend
    newTag: latest
