
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-backend
  namespace: task-manager
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: DB_HOST
              value: "prod-mysql-service"

