apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-app
spec:
  template:
    spec:
      containers:
      - name: task-manager
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
