apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend-service
spec:
  selector:
    app: task-manager-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
