apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

images:
- digest: sha256:363c41bbf33973e133e157e18e4a15b60f49a8ccbe7d8f71b67f7cc81b8f0774
  name: task-manager-backend
  newName: docker.io/tardiatest/task-manager-backend
- digest: sha256:22374e77ff73e0c8ec14d3a068ffafb8367dfb3448e3b50bc2d860a1fa763143
  name: task-manager-frontend
  newName: docker.io/tardiatest/task-manager-frontend

patchesJson6902:
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-backend-service
  target:
    kind: Service
    name: task-manager-backend-service
    version: v1
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-frontend-service
  target:
    kind: Service
    name: task-manager-frontend-service
    version: v1


patchesStrategicMerge:
- replica-patch.yaml
- ingress-patch.yaml
- patch-configmap.yaml
- patch-backend-dbhost.yaml
