apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

images:
- digest: sha256:107e6a4bd7d097989ae7ec098edd4dcf8359456053a0271d4a15bb1c5e3fe416
  name: task-manager-backend
  newName: docker.io/tardiatest/task-manager-backend
- digest: sha256:17e7960b022a9ddff03badcdb13ac130f7e97be094672634b6a163da20b71e6a
  name: task-manager-frontend
  newName: docker.io/tardiatest/task-manager-frontend

patchesJson6902:
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-backend-service
  target:
    kind: Service
    name: task-manager-backend-service
    version: v1
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-frontend-service
  target:
    kind: Service
    name: task-manager-frontend-service
    version: v1


patchesStrategicMerge:
- replica-patch.yaml
- ingress-patch.yaml
- patch-configmap.yaml
- patch-backend-dbhost.yaml
