apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

images:
- digest: sha256:bc9515b6f6c84834c91d83eb01fbe7b40173d39958f867fac267d40015f7e744
  name: task-manager-backend
  newName: docker.io/tardiatest/task-manager-backend
- digest: sha256:c6f0e1eae1d0cb4e4f1388316b6fdcbd61522b1700fc790f8d280ff5de585d3c
  name: task-manager-frontend
  newName: docker.io/tardiatest/task-manager-frontend

patchesJson6902:
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-backend-service
  target:
    kind: Service
    name: task-manager-backend-service
    version: v1
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-frontend-service
  target:
    kind: Service
    name: task-manager-frontend-service
    version: v1


patchesStrategicMerge:
- replica-patch.yaml
- ingress-patch.yaml
- patch-configmap.yaml
- patch-backend-dbhost.yaml
