apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

images:
- digest: sha256:c1c363e7c003cc444ae7a991c2f821d955346c8a00b8a65c6b1604d4950d7980
  name: task-manager-backend
  newName: docker.io/tardiatest/task-manager-backend
- digest: sha256:a64e44da87ac47ebc206f577f2de7bcbde358f0f22d8a4e43fe2767447902856
  name: task-manager-frontend
  newName: docker.io/tardiatest/task-manager-frontend

patchesJson6902:
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-backend-service
  target:
    kind: Service
    name: task-manager-backend-service
    version: v1
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-frontend-service
  target:
    kind: Service
    name: task-manager-frontend-service
    version: v1


patchesStrategicMerge:
- replica-patch.yaml
- ingress-patch.yaml
- patch-configmap.yaml
- patch-backend-dbhost.yaml
