apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

images:
- digest: sha256:287679d5753414651926d2e4e11a2cad6c565738e5867fcac47704447dfe2221
  name: task-manager-backend
  newName: docker.io/tardiatest/task-manager-backend
- digest: sha256:7f649a74a683f2bd13a54f2c8369faac97c24db39d659a486d854e41a417cc4f
  name: task-manager-frontend
  newName: docker.io/tardiatest/task-manager-frontend

patchesJson6902:
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-backend-service
  target:
    kind: Service
    name: task-manager-backend-service
    version: v1
- patch: |
    - op: replace
      path: /metadata/name
      value: task-manager-frontend-service
  target:
    kind: Service
    name: task-manager-frontend-service
    version: v1


patchesStrategicMerge:
- replica-patch.yaml
- ingress-patch.yaml
- patch-configmap.yaml
- patch-backend-dbhost.yaml
