apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Stefaneush/task-manager-k8s-cloud.git
    targetRevision: main
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
