apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-deployment.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - ingress.yaml

images:
  - name: task-manager-frontend
    newTag: latest
  - name: task-manager-backend
    newTag: latest
