apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - backend/
  - frontend/
  - database/
  - ingress.yaml
  - namespace.yaml


images:
  - name: tardiatest/task-manager-frontend
    newTag: latest
  - name: tardiatest/task-manager-backend
    newTag: latest
